
services:
  # Base de Datos PostgreSQL 15
  database:
    image: postgres:15
    container_name: cochatech_db
    environment:
      POSTGRES_DB: cochatech_sistema
      POSTGRES_USER: cochatech_user
      POSTGRES_PASSWORD: cochatech_pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - cochatech_network
    restart: unless-stopped

  # Backend Laravel 11 con PHP 8.2
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cochatech_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - ./backend/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini  # ✅ Esta línea es nueva
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=cochatech_sistema
      - DB_USERNAME=cochatech_user
      - DB_PASSWORD=cochatech_pass
    depends_on:
      - database
    networks:
      - cochatech_network
    restart: unless-stopped

  # Frontend React + Vite + TypeScript
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cochatech_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - cochatech_network
    restart: unless-stopped
    stdin_open: true
    tty: true

  # Apache 2.4.62 (Servidor Web)
  webserver:
    build:
      context: .
      dockerfile: apache/Dockerfile
    container_name: cochatech_webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/sites/:/usr/local/apache2/conf/extra/
      - ./backend:/var/www/html
    depends_on:
      - backend
      - frontend
    networks:
      - cochatech_network
    restart: unless-stopped

  # Redis para Cache y Sesiones
  redis:
    image: redis:7-alpine
    container_name: cochatech_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cochatech_network
    restart: unless-stopped

  # Adminer para administración de BD
  adminer:
    image: adminer
    container_name: cochatech_adminer
    ports:
      - "8080:8080"
    networks:
      - cochatech_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  cochatech_network:
    driver: bridge
